<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KaranevichV" name="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests" tests="11" failures="1" timestamp="8 Aug 2013 11:54:52 GMT" time="0.008" errors="0">
  <testcase name="testBigIntegerAssert_bigNumbersLessCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_bigNumbersEqualObjectCase" time="0.001" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_bigNumbersMoreCase" time="0.001" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_bigNumbersCase" time="0.005" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersFailCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.AssertionError but got org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.AssertionError but got org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 16 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_smallNumbersFailCase(CustomAssertUnitTests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 18 more
]]>
    </failure>
  </testcase> <!-- testBigIntegerAssert_smallNumbersFailCase -->
  <testcase name="testBigIntegerAssert_mixNumbersLessCase" time="0.001" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersMoreCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersNegativeCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersLessCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_mixNumbersMoreCase" time="0.000" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
</testsuite> <!-- com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests -->
